from pydantic import BaseModel
from typing import Optional
from uuid import UUID

class DeviceLoginRequest(BaseModel):
    username: str
    password: str # In real app, this verifies against DB password
    device_name: str
    device_id: str # UUID generated by Client

class FamilyRegistrationRequest(BaseModel):
    family_name: str
    admin_display_name: str
    admin_username: str
    admin_password: str
    device_name: str
    device_id: str

class QuickLoginRequest(BaseModel):
    user_id: UUID
    device_id: str
    pin: Optional[str] = None  # Required if role is PARENT
    redirect_url: Optional[str] = None  # Override redirect (e.g. stay on /game)


class RegisterKidRequest(BaseModel):
    device_id: str
    parent_pin: str
    display_name: str
    avatar_url: Optional[str] = None


class AuthMeResponse(BaseModel):
    id: UUID
    display_name: str
    role: str
    family_id: UUID
    avatar_url: Optional[str] = None
    current_coin: Optional[int] = None

class UserContext(BaseModel):
    id: UUID
    display_name: str
    avatar_url: Optional[str]
    role: str
    has_pin: bool

class DeviceContextResponse(BaseModel):
    is_registered: bool
    family_name: Optional[str] = None
    members: list[UserContext] = []
