from pydantic import BaseModel
from typing import Optional
from uuid import UUID

class DeviceLoginRequest(BaseModel):
    username: str
    password: str # In real app, this verifies against DB password
    device_name: str
    device_id: str # UUID generated by Client

class FamilyRegistrationRequest(BaseModel):
    family_name: str
    admin_display_name: str
    admin_username: str
    admin_password: str
    device_name: str
    device_id: str

class QuickLoginRequest(BaseModel):
    user_id: UUID
    device_id: str
    pin: Optional[str] = None # Required if role is PARENT

class UserContext(BaseModel):
    id: UUID
    display_name: str
    avatar_url: Optional[str]
    role: str
    has_pin: bool

class DeviceContextResponse(BaseModel):
    is_registered: bool
    family_name: Optional[str] = None
    members: list[UserContext] = []
