"""Add payment_cycle and installments_count to loan_accounts

Revision ID: 6e7f97c3792b
Revises: 009
Create Date: 2026-04-12 02:49:33.959825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e7f97c3792b'
down_revision: Union[str, None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    # op.create_unique_constraint('uq_club_user_status', 'club_invitations', ['club_id', 'invited_user_id', 'status']) # Already exists in 001
    op.add_column('loan_accounts', sa.Column('payment_cycle', sa.String(length=20), server_default='ONE_TIME', nullable=True))
    op.add_column('loan_accounts', sa.Column('installments_count', sa.Integer(), server_default='1', nullable=True))
    op.alter_column('personal_projects', 'milestones',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('teen_contracts', 'milestones',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('uq_user_avatar_item', 'user_avatar_items', type_='unique')
    op.alter_column('user_levels', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint('uq_kid_week_reflection', 'weekly_reflections', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_kid_week_reflection', 'weekly_reflections', ['kid_id', 'week_start'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_levels', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_unique_constraint('uq_user_avatar_item', 'user_avatar_items', ['user_id', 'item_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('teen_contracts', 'milestones',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('personal_projects', 'milestones',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('loan_accounts', 'installments_count')
    op.drop_column('loan_accounts', 'payment_cycle')
    op.drop_constraint('uq_club_user_status', 'club_invitations', type_='unique')
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('SYSTEM', 'CLUB_INVITE', 'KID_CLUB_INVITE', 'TASK_ASSIGNED', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('action_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    # ### end Alembic commands ###
