name: CI/CD KidCoin

on:
  push:
    branches: [ "main" ] # Tự động chạy khi bạn push vào nhánh main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kidcoin-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Oracle via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/kidcoin-project
            # Pull bản mới nhất từ Docker Hub
            docker compose pull
            # Khởi động lại các container với bản mới
            docker compose up -d
            # Dọn dẹp các bản cũ để tiết kiệm ổ cứng 1GB RAM
            docker image prune -f
